# Generated by Django 6.0.3 on 2026-03-29 15:38

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Departement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom_departement', models.CharField(max_length=100)),
                ('budget_annuel', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('manager', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='departement_dirige', to='accounts.employe')),
            ],
        ),
        migrations.CreateModel(
            name='Projet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom_projet', models.CharField(max_length=100)),
                ('date_limite', models.DateField()),
                ('statut', models.CharField(default='En cours', max_length=50)),
                ('chef_projet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projets_diriges', to='accounts.employe')),
                ('equipe', models.ManyToManyField(blank=True, related_name='projets_affectes', to='accounts.employe')),
            ],
        ),
    ]
