# Generated by Django 6.0.3 on 2026-05-06 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employe',
            name='statut',
            field=models.CharField(choices=[('ACTIF', 'Actif'), ('DEMISSIONNAIRE', 'Demissionnaire'), ('CONGE', 'Congé'), ('LICENCIE', 'Licencié')], default='ACTIF', max_length=20),
        ),
    ]
