# Generated by Django 6.0.3 on 2026-05-06 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_employe_statut'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchiveEmploye',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150)),
                ('matricule', models.CharField(max_length=50)),
                ('poste_titre', models.CharField(blank=True, max_length=100, null=True)),
                ('departement_nom', models.CharField(blank=True, max_length=100, null=True)),
                ('date_depart', models.DateTimeField(auto_now_add=True)),
                ('statut_depart', models.CharField(choices=[('DEMISSIONNAIRE', 'Démission'), ('LICENCIE', 'Licenciement'), ('FIN_CDD', 'Fin de contrat CDD'), ('RETRAITE', 'Départ en retraite')], max_length=50)),
                ('matrice_competences_archive', models.JSONField(blank=True, default=list, null=True)),
            ],
            options={
                'verbose_name': 'Archive Employé',
                'verbose_name_plural': 'Archives Employés',
            },
        ),
    ]
