# Generated by Django 6.0.3 on 2026-05-06 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_archiveemploye'),
    ]

    operations = [
        migrations.AddField(
            model_name='employe',
            name='salaire',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='employe',
            name='type_contrat',
            field=models.CharField(choices=[('CDI', 'CDI'), ('CDD', 'CDD'), ('STAGE', 'Stage'), ('FREELANCE', 'Freelance')], default='CDI', max_length=20),
        ),
    ]
