# Generated by Django 6.0.3 on 2026-05-15 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_employe_salaire_employe_type_contrat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archiveemploye',
            name='date_depart',
            field=models.DateField(blank=True, null=True),
        ),
    ]
