# Generated by Django 6.0.3 on 2026-03-29 15:38

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contrat',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField(blank=True, null=True)),
                ('type_contrat', models.CharField(choices=[('CDI', 'CDI'), ('CDD', 'CDD'), ('STAGE', 'Stage')], max_length=20)),
                ('salaire_mensuel', models.DecimalField(decimal_places=2, max_digits=10)),
                ('jours_preavis', models.IntegerField(default=30)),
                ('employe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contrats', to='accounts.employe')),
            ],
        ),
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_evaluation', models.DateField()),
                ('note_comportementale', models.FloatField()),
                ('commentaire', models.TextField(blank=True, null=True)),
                ('employe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='accounts.employe')),
            ],
        ),
        migrations.CreateModel(
            name='FichePaie',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('periode_mois', models.IntegerField()),
                ('periode_annee', models.IntegerField()),
                ('salaire_base', models.DecimalField(decimal_places=2, max_digits=10)),
                ('deductions_absences', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('primes_evaluation', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('net_a_payer', models.DecimalField(decimal_places=2, max_digits=10)),
                ('employe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fiches_paie', to='accounts.employe')),
            ],
        ),
    ]
