# Generated by Django 6.0.3 on 2026-05-08 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0003_rename_primes_evaluation_fichepaie_primes_supp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presencemanuelle',
            name='statut',
            field=models.CharField(choices=[('PRESENT', 'Présent'), ('ABSENT', 'Absent'), ('SUPP', 'Jour Supp/Weekend'), ('REPOS', 'Jour de Repos')], default='PRESENT', max_length=10),
        ),
    ]
