# Generated by Django 6.0.3 on 2026-03-29 15:38

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DemandeConge',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('statut', models.CharField(choices=[('ATTENTE', 'En attente'), ('VALIDE', 'Validé'), ('REFUSE', 'Refusé')], default='ATTENTE', max_length=20)),
                ('motif', models.TextField()),
                ('employe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conges', to='accounts.employe')),
            ],
        ),
        migrations.CreateModel(
            name='PointageIoT',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField()),
                ('id_capteur', models.CharField(max_length=50)),
                ('est_justifie', models.BooleanField(default=False)),
                ('employe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pointages', to='accounts.employe')),
            ],
        ),
    ]
