# Generated by Django 6.0.3 on 2026-04-29 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pointageiot',
            name='type_pointage',
            field=models.CharField(choices=[('ENTREE', 'Entrée'), ('SORTIE', 'Sortie')], default='ENTREE', max_length=10),
        ),
    ]
