# Generated by Django 6.0.3 on 2026-05-06 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_pointageiot_type_pointage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pointageiot',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
