# Generated by Django 6.0.3 on 2026-05-08 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_alter_pointageiot_timestamp'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DemandeConge',
        ),
    ]
